#!/usr/bin/env python3
"""
Re-encodes bmp/*.bmp (Ruby's expression art) as 8bpp grayscale BMPs and emits each one as a
`static const uint8_t[]` C header under src/ruby/embeddedArt/, so the art ships inside the
firmware image instead of requiring users to copy files onto an SD card.

8bpp-with-identity-palette re-encoding (rather than embedding the original 24/32bpp files
verbatim) cuts each image from ~115 KB to ~30 KB — about 4x smaller, ~960 KB down to ~167 KB
total for all six — while still being a plain, uncompressed BMP the existing on-device parser
(lib/GfxRenderer/Bitmap.cpp) already handles with no changes: same BI_RGB/8bpp/palette path it
already uses for any other paletted BMP. Run manually (`python3 scripts/generate_embedded_art.py`)
whenever bmp/*.bmp changes — this is a one-off asset step like fontconvert.py, not part of the
PlatformIO build.
"""

import os
import struct

from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
SRC_DIR = os.path.join(REPO_ROOT, "bmp")
OUT_DIR = os.path.join(REPO_ROOT, "src", "ruby", "embeddedArt")

IMAGE_NAMES = ["excited", "curious", "content", "bored", "lonely", "sleep"]

DIB_HEADER_SIZE = 40  # BITMAPINFOHEADER
FILE_HEADER_SIZE = 14
BYTES_PER_LINE = 16


def make_8bpp_bmp_bytes(im: Image.Image) -> bytes:
    """Re-encodes `im` as a bottom-up, uncompressed, 8bpp grayscale BMP with an identity palette
    (palette[i] = (i, i, i)), so the firmware's own luminance formula reproduces the same value it
    was given — this is a lossless grayscale re-encode, not a re-dither."""
    gray = im.convert("L")
    w, h = gray.size
    row_bytes = (w + 3) // 4 * 4  # 8bpp rows padded to a 4-byte boundary
    palette = b"".join(bytes([i, i, i, 0]) for i in range(256))  # B, G, R, reserved

    px = gray.load()
    rows = []
    for y in range(h - 1, -1, -1):  # bottom-up row order, standard BMP orientation
        row = bytearray(row_bytes)
        for x in range(w):
            row[x] = px[x, y]
        rows.append(bytes(row))
    pixel_data = b"".join(rows)

    off_bits = FILE_HEADER_SIZE + DIB_HEADER_SIZE + len(palette)
    file_size = off_bits + len(pixel_data)

    file_header = struct.pack("<2sIHHI", b"BM", file_size, 0, 0, off_bits)
    dib_header = struct.pack(
        "<IiiHHIIiiII",
        DIB_HEADER_SIZE, w, h, 1, 8, 0, len(pixel_data), 2835, 2835, 256, 0,
    )
    return file_header + dib_header + palette + pixel_data


def emit_header(name: str, data: bytes) -> str:
    var = f"{name}_bmp"
    path = os.path.join(OUT_DIR, f"{var}.h")
    with open(path, "w") as f:
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"// Generated by scripts/generate_embedded_art.py from bmp/{name}.bmp — do not edit by\n")
        f.write("// hand, re-run the script instead. 8bpp grayscale BMP, identity palette.\n")
        f.write(f"static const uint8_t {var}_data[{len(data)}] = {{\n")
        for i in range(0, len(data), BYTES_PER_LINE):
            chunk = data[i:i + BYTES_PER_LINE]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n")
    return path


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    total = 0
    for name in IMAGE_NAMES:
        src_path = os.path.join(SRC_DIR, f"{name}.bmp")
        with Image.open(src_path) as im:
            data = make_8bpp_bmp_bytes(im)
        out_path = emit_header(name, data)
        print(f"{name}: {os.path.relpath(src_path, REPO_ROOT)} -> {os.path.relpath(out_path, REPO_ROOT)} "
              f"({len(data)} bytes)")
        total += len(data)
    print(f"total: {total} bytes across {len(IMAGE_NAMES)} images")


if __name__ == "__main__":
    main()
