#pragma once

#include <GfxRenderer.h>

#include "RubyState.h"

// Draws Ruby: bitmap art per expression, baked into the firmware image (RubyEmbeddedArt.h,
// generated by scripts/generate_embedded_art.py from bmp/*.bmp) so it works with no SD-card setup
// out of the box. An SD card at /bmp/<expression>.bmp — see the repo's bmp/ directory — is still
// checked first and overrides the built-in art if present, letting anyone swap in custom art
// without recompiling. Falls back further still to a jittered silhouette polygon with procedural
// eyes/mouth/noise only if a bitmap somehow fails to parse.
// Unlike a pet that grows through stages, there's one fixed identity: what changes from frame to
// frame is the *expression*, driven by RubyExpression, the same way Pwnagotchi's face reacts to
// what it just found rather than the pet "leveling up."
//
// This is also what gets redrawn on every "strict partial refresh" tick: callers own clearing and
// redrawing only the box below, then calling GfxRenderer::displayBuffer(FAST_REFRESH) — see
// DashboardActivity — so the surrounding static dashboard content is never touched.
class RubySpriteRenderer {
 public:
  // Draws into a boxSize x boxSize square with top-left at (x, y). animFrame cycles the jitter
  // and eye state (2 frames is enough for a believable "breathing"/blink loop at a slow tick).
  static void draw(GfxRenderer& renderer, int x, int y, int boxSize, RubyExpression expression,
                   uint8_t animFrame);

  // Small portrait used on the sleep screen and boot splash — same silhouette generator, fixed
  // frame 0, SLEEPING expression (closed eyes, no noise), kept perfectly static across frames.
  static void drawPortrait(GfxRenderer& renderer, int x, int y, int boxSize);
};
